import HeaderDashboard from "@/components/headerDashboard/HeaderDashboard";
import { withSSRAuth } from "@/utils/withSSRAuth";
import Head from "next/head";
import React from "react";
import CriarProjetoContent from "@/components/criarProjeto/CriarProjetoContent";

export default function areasExperiencia() {
  return (
    <div>
      <Head>
        <title>BT | Criar Projeto</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/*  <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <HeaderDashboard />
      <CriarProjetoContent />
    </div>
  );
}
/* export const getServerSideProps = withSSRAuth(async (ctx) => {
  return {
    props: {},
  };
});
 */
