import AreasExperienciaContent from "@/components/areasExperiencia/AreasExperienciaContent";
import HeaderDashboard from "@/components/headerDashboard/HeaderDashboard";
import { setupApiClient } from "@/services/api";
import { withSSRAuth } from "@/utils/withSSRAuth";
import Head from "next/head";
import React from "react";

export default function areasExperiencia() {
  return (
    <div>
      <Head>
        <title>BT | Áreas de Experiência</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/*  <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <HeaderDashboard />
      <AreasExperienciaContent />
    </div>
  );
}

export const getServerSideProps = withSSRAuth(async (ctx) => {
  return {
    props: {},
  };
});
