import Head from "next/head";
import Hero from "@/components/hero/Hero";
import HeaderApp from "@/components/headerApp/HeaderApp";
import { withSSRGuest } from "@/utils/withSSRGuest";

export default function home() {
  return (
    <>
      <Head>
        <title>BT | Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel='icon' href='/favicon2.png' /> */}
      </Head>
      <HeaderApp />
      <main>
        <Hero />
      </main>
    </>
  );
}

export const getServerSideProps = withSSRGuest(async (ctx) => {
  return {
    props: {},
  };
});
