import HeaderAuth from "@/components/headerAuth/HeaderAuth";
import Head from "next/head";
import React from "react";
import LoginContent from "@/components/loginContent/LoginContent";
import { withSSRGuest } from "@/utils/withSSRGuest";

export default function login() {
  return (
    <>
      <Head>
        <title>BT | Login</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <HeaderAuth />
      <LoginContent />
    </>
  );
}

export const getServerSideProps = withSSRGuest(async (ctx) => {
  return {
    props: {},
  };
});
