import HeaderDashboard from "@/components/headerDashboard/HeaderDashboard";
import MeusProjetosContent from "@/components/meusProjetos/MeusProjetosContent";
import { withSSRAuth } from "@/utils/withSSRAuth";
import Head from "next/head";
import React from "react";

export default function meusProjetos() {
  return (
    <div>
      <Head>
        <title>BT | Meus Projetos</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/*  <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <HeaderDashboard />
      <MeusProjetosContent />
    </div>
  );
}

export const getServerSideProps = withSSRAuth(async (ctx) => {
  return {
    props: {},
  };
});
