import HeaderDashboard from "@/components/headerDashboard/HeaderDashboard";
import MeusProjetosContent from "@/components/meusProjetos/MeusProjetosContent";
import { setupApiClient } from "@/services/api";
import { withSSRAuth } from "@/utils/withSSRAuth";
import Head from "next/head";
import React from "react";

type userMe = {
  id: number;
  name: string;
  email: string;
  projects: [];
  experiences: [];
};

type userMeProjects = {
  id: number;
  name: string;
  description: string;
  contact: string;
  experiences: [];
  candidates: [];
};

interface Props {
  userMe: userMe;
  userMeProjects: userMeProjects[];
}

export default function meusProjetos({ userMe, userMeProjects }: Props) {
  return (
    <div>
      <Head>
        <title>BT | Meus Projetos</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/*  <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <HeaderDashboard />
      <MeusProjetosContent userMe={userMe} userMeProjects={userMeProjects} />
    </div>
  );
}

export const getServerSideProps = withSSRAuth(async (ctx) => {
  const apiClient = setupApiClient(ctx);
  let userMe = null;
  let userMeProjects = [];
  try {
    const responseUserMeProjects = await apiClient.get("/me/projects");
    userMeProjects = responseUserMeProjects.data;
    console.log(userMeProjects);
    const responseUserMe = await apiClient.get("/me");
    userMe = responseUserMe.data;
  } catch (err) {
    console.log(err);
  }
  return {
    props: {
      userMe: userMe,
      userMeProjects: userMeProjects,
    },
  };
});
