import HeaderDashboard from "@/components/headerDashboard/HeaderDashboard";
import PainelContent from "@/components/painelContent/PainelContent";
import { withSSRGuest } from "@/utils/withSSRGuest";
import Head from "next/head";
import React from "react";

export default function dashboard() {
  return (
    <div>
      <Head>
        <title>Painel</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HeaderDashboard />
      <PainelContent />
    </div>
  );
}

export const getServerSideProps = withSSRGuest(async (ctx) => {
  return {
    props: {},
  };
});
