import HeaderDashboard from "@/components/headerDashboard/HeaderDashboard";
import PerfilContent from "@/components/perfil/PerfilContent";
import { withSSRAuth } from "@/utils/withSSRAuth";
import Head from "next/head";
import React from "react";

export default function perfil() {
  return (
    <div>
      <Head>
        <title>BT | Perfil</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/*  <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <HeaderDashboard />
      <PerfilContent />
    </div>
  );
}

/* export const getServerSideProps = withSSRAuth(async (ctx) => {
  return {
    props: {},
  };
}); */
