import HeaderDashboard from "@/components/headerDashboard/HeaderDashboard";
import PerfilContent from "@/components/perfil/PerfilContent";
import { setupApiClient } from "@/services/api";
import { withSSRAuth } from "@/utils/withSSRAuth";
import Head from "next/head";
import React from "react";

type userMe = {
  id: number;
  name: string;
  email: string;
  projects: [];
  experiences: [];
};

interface Props {
  userMe: userMe;
}

export default function perfil({ userMe }: Props) {
  return (
    <div>
      <Head>
        <title>BT | Perfil</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/*  <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <HeaderDashboard />
      <PerfilContent userMe={userMe} />
    </div>
  );
}

export const getServerSideProps = withSSRAuth(async (ctx) => {
  const apiClient = setupApiClient(ctx);
  let userMe = null;
  try {
    const responseUserMe = await apiClient.get("/me");
    userMe = responseUserMe.data;
  } catch (err) {
    console.log(err);
  }
  return {
    props: {
      userMe: userMe,
    },
  };
});
